//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNotifier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
        }
        public Cours( int id , int smes , string cou , string tea)
        {
            this.Id = id;
            this.SemesterNo = smes;
            this.Teacher = tea;
            this.Courses = cou;
        }
        public int Id { get; set; }
        public int SemesterNo { get; set; }
        public string Courses { get; set; }
        public string Teacher { get; set; }
    }
}
