//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentNotifier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public Nullable<int> TId { get; set; }
        public string Course { get; set; }
        public string notification1 { get; set; }
        public string filePath { get; set; }
        public Nullable<int> semester { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
